-- These inputs are deliberately not generated by pg_dump.
\! touch /tmp/pv-import-should-never-run
\include /tmp/pv-import-should-never-run
\copy public.proof FROM PROGRAM 'touch /tmp/pv-import-should-never-run'
\connect unrelated_project
CREATE ROLE intruder SUPERUSER;
