[[resource]]
name = "php"
default_track = "8.4"

[[resource]]
name = "frankenphp"
default_track = "8.4"

[[resource]]
name = "composer"
default_track = "2"

[[resource]]
name = "redis"
default_track = "8.2"

[[resource]]
name = "mysql"
default_track = "8.4"

[[resource]]
name = "postgres"
default_track = "18"

[[resource]]
name = "mailpit"
default_track = "1"

[[resource]]
name = "rustfs"
default_track = "1"
