[recipe]
resources = ["php", "frankenphp"]
default_track = "8.4"
platforms = ["darwin-arm64", "darwin-amd64"]
minimum_pv_version = "0.1.0"
pv_build_revision = "pv1"
license_files = ["LICENSE"]
notice_files = ["NOTICE"]

[php]
deployment_target = "13.0"
build_extensions = [
  "bcmath",
  "ctype",
  "curl",
  "dom",
  "fileinfo",
  "filter",
  "iconv",
  "intl",
  "libxml",
  "mbstring",
  "openssl",
  "pcntl",
  "pdo",
  "pdo_mysql",
  "pdo_pgsql",
  "pdo_sqlite",
  "phar",
  "posix",
  "redis",
  "session",
  "simplexml",
  "sodium",
  "sqlite3",
  "tokenizer",
  "xml",
  "xmlreader",
  "xmlwriter",
  "zip",
  "zlib",
]
expected_extensions = [
  "bcmath",
  "ctype",
  "curl",
  "dom",
  "fileinfo",
  "filter",
  "hash",
  "iconv",
  "intl",
  "json",
  "libxml",
  "mbstring",
  "openssl",
  "pcntl",
  "pcre",
  "pdo",
  "pdo_mysql",
  "pdo_pgsql",
  "pdo_sqlite",
  "phar",
  "posix",
  "redis",
  "session",
  "simplexml",
  "sodium",
  "sqlite3",
  "tokenizer",
  "xml",
  "xmlreader",
  "xmlwriter",
  "zip",
  "zlib",
]

[frankenphp]
version = "1.12.3"
source_url = "https://github.com/php/frankenphp/archive/refs/tags/v1.12.3.tar.gz"
source_sha256 = "2996fb95bbdf8410847fdcd59df04cd2e297568f6472ebe488af5fb5f3c79363"

[[tracks]]
name = "8.2"
php_version = "8.2.31"
php_source_url = "https://www.php.net/distributions/php-8.2.31.tar.gz"
php_source_sha256 = "083c2f61cc5f527eb293c4c468a91af46a9678785957e023b2796a9db290d870"

[[tracks]]
name = "8.3"
php_version = "8.3.31"
php_source_url = "https://www.php.net/distributions/php-8.3.31.tar.gz"
php_source_sha256 = "4e7baaf0a690e954a20e7ced3dd633ce8cb8094e2b6b612a55e703ecbbdcbf4f"

[[tracks]]
name = "8.4"
php_version = "8.4.20"
php_source_url = "https://www.php.net/distributions/php-8.4.20.tar.gz"
php_source_sha256 = "a2def5d534d57c6a0236f2265de7537608af871900a4f7955eff463e9e38247d"
