[recipe]
resources = ["php", "frankenphp"]
default_track = "8.5"
platforms = ["darwin-arm64", "darwin-amd64"]
minimum_pv_version = "0.1.0"
pv_build_revision = "pv1"
license_files = ["LICENSE"]
notice_files = ["NOTICE"]

[php]
deployment_target = "13.0"
build_extensions = [
  "bcmath",
  "ctype",
  "curl",
  "dom",
  "fileinfo",
  "filter",
  "iconv",
  "intl",
  "libxml",
  "mbstring",
  "openssl",
  "pcntl",
  "pdo",
  "pdo_mysql",
  "pdo_pgsql",
  "pdo_sqlite",
  "pdo_sqlsrv",
  "phar",
  "posix",
  "redis",
  "session",
  "simplexml",
  "sodium",
  "sqlite3",
  "sqlsrv",
  "tokenizer",
  "xml",
  "xmlreader",
  "xmlwriter",
  "zip",
  "zlib",
]
expected_extensions = [
  "bcmath",
  "ctype",
  "curl",
  "dom",
  "fileinfo",
  "filter",
  "hash",
  "iconv",
  "intl",
  "json",
  "libxml",
  "mbstring",
  "openssl",
  "pcntl",
  "pcre",
  "pdo",
  "pdo_mysql",
  "pdo_pgsql",
  "pdo_sqlite",
  "pdo_sqlsrv",
  "phar",
  "posix",
  "redis",
  "session",
  "simplexml",
  "sodium",
  "sqlite3",
  "sqlsrv",
  "tokenizer",
  "xml",
  "xmlreader",
  "xmlwriter",
  "zip",
  "zlib",
]

[frankenphp]
version = "1.12.4"
source_url = "https://github.com/php/frankenphp/archive/refs/tags/v1.12.4.tar.gz"
source_sha256 = "c8af6ff0608f322d564e80c0c37fb7b766adf067c5f0e9bc7b1ed9e0315d8ba1"

[[tracks]]
name = "8.3"
php_version = "8.3.31"
php_source_url = "https://www.php.net/distributions/php-8.3.31.tar.gz"
php_source_sha256 = "4e7baaf0a690e954a20e7ced3dd633ce8cb8094e2b6b612a55e703ecbbdcbf4f"

[[tracks]]
name = "8.4"
php_version = "8.4.22"
php_source_url = "https://www.php.net/distributions/php-8.4.22.tar.gz"
php_source_sha256 = "a012c2c9724baf214a70b41b40a7e130906b8855e54268afa5bc4ae17bc9d823"

[[tracks]]
name = "8.5"
php_version = "8.5.7"
php_source_url = "https://www.php.net/distributions/php-8.5.7.tar.gz"
php_source_sha256 = "e5eba93fd6dd3241d0e61e932eb99a3783b40568553fb0e511b660ecd863a049"
