[recipe]
resources = ["redis"]
default_track = "8.8"
platforms = ["darwin-arm64", "darwin-amd64"]
minimum_pv_version = "0.1.0"
pv_build_revision = "pv1"
license_files = ["LICENSE"]
notice_files = ["NOTICE", "THIRD-PARTY-NOTICES"]

[artifact]
payload_paths = ["bin/redis-server", "bin/redis-cli"]

[[tracks]]
name = "8.8"
upstream_version = "8.8.0"
source_url = "https://download.redis.io/releases/redis-8.8.0.tar.gz"
source_sha256 = "88422181efb0c9c0abba332e3e391d409e1e13714b838931669235e5796f704b"
