[package]
name = "pv-fake"
version = "0.2.5"
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
camino = { workspace = true }
futures-util = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true, features = ["server"] }
hyper-util = { workspace = true }
pgwire = { workspace = true }
rcgen = { workspace = true }
redis-protocol = { workspace = true }
rustls = { workspace = true }
s3s = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
socket2 = { workspace = true }
state = { path = "../state" }
time = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, features = ["pipe"] }

[dev-dependencies]
camino-tempfile = { workspace = true }

[target.'cfg(target_os = "macos")'.dev-dependencies]
platform = { path = "../platform" }
