[recipe]
resources = ["postgres"]
default_track = "18"
platforms = ["darwin-arm64", "darwin-amd64"]
minimum_pv_version = "0.1.0"
pv_build_revision = "pv1"
license_files = ["LICENSE", "OPENSSL-LICENSE"]
notice_files = ["NOTICE", "THIRD-PARTY-NOTICES"]

[artifact]
payload_paths = [
  "bin/postgres",
  "bin/initdb",
  "bin/pg_ctl",
  "bin/psql",
  "bin/pg_restore",
  "lib/libcrypto.3.dylib",
  "lib/libssl.3.dylib",
  "lib/postgresql/pg_trgm.dylib",
  "lib/postgresql/pgcrypto.dylib",
  "lib/postgresql/sslinfo.dylib",
  "share/extension/pg_trgm.control",
  "share/extension/pgcrypto.control",
  "share/extension/sslinfo.control",
]

[[tracks]]
name = "17"
upstream_version = "17.11"
source_url = "https://ftp.postgresql.org/pub/source/v17.11/postgresql-17.11.tar.gz"
source_sha256 = "5367f6fb2ec97efe1eb2e0c7926bb33438e51b0bd3a9733b88498056a7dc9a7e"

[[tracks]]
name = "18"
upstream_version = "18.6"
source_url = "https://ftp.postgresql.org/pub/source/v18.6/postgresql-18.6.tar.gz"
source_sha256 = "983ee554ec53dbeb9b70797bef9fcf4e67e117e7e48ca1463cc80b3ff8e8ff3f"
